// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: wire.proto

package wirev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CipherSuite specifies the cryptographic algorithm suite used for envelope encryption.
type CipherSuite int32

const (
	CipherSuite_CIPHER_SUITE_UNSPECIFIED CipherSuite = 0
	// RFC 9180: DHKEM(X25519, HKDF-SHA256) + HKDF-SHA256 + AES-256-GCM
	CipherSuite_CIPHER_SUITE_DHKEM_X25519_AES256_GCM CipherSuite = 1
	// RFC 9180: DHKEM(X25519, HKDF-SHA256) + HKDF-SHA256 + ChaCha20Poly1305
	CipherSuite_CIPHER_SUITE_DHKEM_X25519_CHACHA20_POLY1305 CipherSuite = 2
)

// Enum value maps for CipherSuite.
var (
	CipherSuite_name = map[int32]string{
		0: "CIPHER_SUITE_UNSPECIFIED",
		1: "CIPHER_SUITE_DHKEM_X25519_AES256_GCM",
		2: "CIPHER_SUITE_DHKEM_X25519_CHACHA20_POLY1305",
	}
	CipherSuite_value = map[string]int32{
		"CIPHER_SUITE_UNSPECIFIED":                    0,
		"CIPHER_SUITE_DHKEM_X25519_AES256_GCM":        1,
		"CIPHER_SUITE_DHKEM_X25519_CHACHA20_POLY1305": 2,
	}
)

func (x CipherSuite) Enum() *CipherSuite {
	p := new(CipherSuite)
	*p = x
	return p
}

func (x CipherSuite) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CipherSuite) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_proto_enumTypes[0].Descriptor()
}

func (CipherSuite) Type() protoreflect.EnumType {
	return &file_wire_proto_enumTypes[0]
}

func (x CipherSuite) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CipherSuite.Descriptor instead.
func (CipherSuite) EnumDescriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{0}
}

// CompressionCodec defines optional compression applied to plaintext prior to encryption.
type CompressionCodec int32

const (
	CompressionCodec_COMPRESSION_NONE   CompressionCodec = 0
	CompressionCodec_COMPRESSION_ZSTD   CompressionCodec = 1
	CompressionCodec_COMPRESSION_SNAPPY CompressionCodec = 2
)

// Enum value maps for CompressionCodec.
var (
	CompressionCodec_name = map[int32]string{
		0: "COMPRESSION_NONE",
		1: "COMPRESSION_ZSTD",
		2: "COMPRESSION_SNAPPY",
	}
	CompressionCodec_value = map[string]int32{
		"COMPRESSION_NONE":   0,
		"COMPRESSION_ZSTD":   1,
		"COMPRESSION_SNAPPY": 2,
	}
)

func (x CompressionCodec) Enum() *CompressionCodec {
	p := new(CompressionCodec)
	*p = x
	return p
}

func (x CompressionCodec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompressionCodec) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_proto_enumTypes[1].Descriptor()
}

func (CompressionCodec) Type() protoreflect.EnumType {
	return &file_wire_proto_enumTypes[1]
}

func (x CompressionCodec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompressionCodec.Descriptor instead.
func (CompressionCodec) EnumDescriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{1}
}

// FrameType identifies the semantic payload carried inside a StreamingInferenceFrame.
type FrameType int32

const (
	FrameType_FRAME_TYPE_UNSPECIFIED FrameType = 0
	// Streaming token chunk (AES-GCM encrypted delta token or SSE event)
	FrameType_FRAME_TYPE_TOKEN_DELTA FrameType = 1
	// Non-streaming full completion payload
	FrameType_FRAME_TYPE_COMPLETION FrameType = 2
	// Stream termination signal (equivalent to [DONE])
	FrameType_FRAME_TYPE_STREAM_END FrameType = 3
	// Enclave error frame (encrypted error message)
	FrameType_FRAME_TYPE_ERROR FrameType = 4
	// Heartbeat / keepalive frame to prevent proxy timeouts during prefill
	FrameType_FRAME_TYPE_HEARTBEAT FrameType = 5
)

// Enum value maps for FrameType.
var (
	FrameType_name = map[int32]string{
		0: "FRAME_TYPE_UNSPECIFIED",
		1: "FRAME_TYPE_TOKEN_DELTA",
		2: "FRAME_TYPE_COMPLETION",
		3: "FRAME_TYPE_STREAM_END",
		4: "FRAME_TYPE_ERROR",
		5: "FRAME_TYPE_HEARTBEAT",
	}
	FrameType_value = map[string]int32{
		"FRAME_TYPE_UNSPECIFIED": 0,
		"FRAME_TYPE_TOKEN_DELTA": 1,
		"FRAME_TYPE_COMPLETION":  2,
		"FRAME_TYPE_STREAM_END":  3,
		"FRAME_TYPE_ERROR":       4,
		"FRAME_TYPE_HEARTBEAT":   5,
	}
)

func (x FrameType) Enum() *FrameType {
	p := new(FrameType)
	*p = x
	return p
}

func (x FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_wire_proto_enumTypes[2].Descriptor()
}

func (FrameType) Type() protoreflect.EnumType {
	return &file_wire_proto_enumTypes[2]
}

func (x FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameType.Descriptor instead.
func (FrameType) EnumDescriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{2}
}

// EncryptedInferenceRequest is the outer wire envelope sent by the client to POST /v1/chat/completions.
type EncryptedInferenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol wire version (must be 1 for v1)
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Cryptographic ciphersuite used for HPKE encryption
	CipherSuite CipherSuite `protobuf:"varint,2,opt,name=cipher_suite,json=cipherSuite,proto3,enum=cevell.wire.v1.CipherSuite" json:"cipher_suite,omitempty"`
	// 32-byte client ephemeral X25519 public key (DHKEM sender public key)
	ClientEphemeralPublicKey []byte `protobuf:"bytes,3,opt,name=client_ephemeral_public_key,json=clientEphemeralPublicKey,proto3" json:"client_ephemeral_public_key,omitempty"`
	// 12-byte initialization vector / nonce for request AEAD decryption
	Nonce []byte `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Encrypted ciphertext containing the OpenAI-compatible JSON request payload (and AEAD tag)
	EncryptedPayload []byte `protobuf:"bytes,5,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	// Optional: 32-byte SHA-256 digest of the CVM's attestation document or TLS fingerprint.
	// Pins the request cryptographically to an attested instance, preventing replay/relay attacks.
	AttestationBindingHash []byte `protobuf:"bytes,6,opt,name=attestation_binding_hash,json=attestationBindingHash,proto3" json:"attestation_binding_hash,omitempty"`
	// Client-generated unique correlation ID for tracking and idempotency
	RequestId string `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Compression codec applied to plaintext before AEAD encryption
	Compression CompressionCodec `protobuf:"varint,8,opt,name=compression,proto3,enum=cevell.wire.v1.CompressionCodec" json:"compression,omitempty"`
	// Reserved for Ox ecosystem control flags (e.g. ox-fleet failover hints, ox-shield routing)
	EcosystemMetadata map[string]string `protobuf:"bytes,9,rep,name=ecosystem_metadata,json=ecosystemMetadata,proto3" json:"ecosystem_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EncryptedInferenceRequest) Reset() {
	*x = EncryptedInferenceRequest{}
	mi := &file_wire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedInferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedInferenceRequest) ProtoMessage() {}

func (x *EncryptedInferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedInferenceRequest.ProtoReflect.Descriptor instead.
func (*EncryptedInferenceRequest) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptedInferenceRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EncryptedInferenceRequest) GetCipherSuite() CipherSuite {
	if x != nil {
		return x.CipherSuite
	}
	return CipherSuite_CIPHER_SUITE_UNSPECIFIED
}

func (x *EncryptedInferenceRequest) GetClientEphemeralPublicKey() []byte {
	if x != nil {
		return x.ClientEphemeralPublicKey
	}
	return nil
}

func (x *EncryptedInferenceRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptedInferenceRequest) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *EncryptedInferenceRequest) GetAttestationBindingHash() []byte {
	if x != nil {
		return x.AttestationBindingHash
	}
	return nil
}

func (x *EncryptedInferenceRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EncryptedInferenceRequest) GetCompression() CompressionCodec {
	if x != nil {
		return x.Compression
	}
	return CompressionCodec_COMPRESSION_NONE
}

func (x *EncryptedInferenceRequest) GetEcosystemMetadata() map[string]string {
	if x != nil {
		return x.EcosystemMetadata
	}
	return nil
}

// StreamingInferenceFrame is a framed binary AEAD message emitted over HTTP chunked streaming.
type StreamingInferenceFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonically increasing sequence number (0, 1, 2, ...)
	// Prevents frame replay, undetected drops, and guarantees ordered assembly.
	SequenceNumber uint32 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// Semantic type of the frame
	FrameType FrameType `protobuf:"varint,2,opt,name=frame_type,json=frameType,proto3,enum=cevell.wire.v1.FrameType" json:"frame_type,omitempty"`
	// AES-256-GCM encrypted payload (delta token JSON, completion JSON, or error)
	EncryptedPayload []byte `protobuf:"bytes,3,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	// 16-byte AES-GCM authentication tag for this frame
	AuthTag []byte `protobuf:"bytes,4,opt,name=auth_tag,json=authTag,proto3" json:"auth_tag,omitempty"`
	// Generation timestamp at enclave exit (Unix nanoseconds) for latency and audit telemetry
	TimestampNs   int64 `protobuf:"varint,5,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingInferenceFrame) Reset() {
	*x = StreamingInferenceFrame{}
	mi := &file_wire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingInferenceFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingInferenceFrame) ProtoMessage() {}

func (x *StreamingInferenceFrame) ProtoReflect() protoreflect.Message {
	mi := &file_wire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingInferenceFrame.ProtoReflect.Descriptor instead.
func (*StreamingInferenceFrame) Descriptor() ([]byte, []int) {
	return file_wire_proto_rawDescGZIP(), []int{1}
}

func (x *StreamingInferenceFrame) GetSequenceNumber() uint32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *StreamingInferenceFrame) GetFrameType() FrameType {
	if x != nil {
		return x.FrameType
	}
	return FrameType_FRAME_TYPE_UNSPECIFIED
}

func (x *StreamingInferenceFrame) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *StreamingInferenceFrame) GetAuthTag() []byte {
	if x != nil {
		return x.AuthTag
	}
	return nil
}

func (x *StreamingInferenceFrame) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

var File_wire_proto protoreflect.FileDescriptor

const file_wire_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"wire.proto\x12\x0ecevell.wire.v1\"\xcb\x04\n" +
	"\x19EncryptedInferenceRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12>\n" +
	"\fcipher_suite\x18\x02 \x01(\x0e2\x1b.cevell.wire.v1.CipherSuiteR\vcipherSuite\x12=\n" +
	"\x1bclient_ephemeral_public_key\x18\x03 \x01(\fR\x18clientEphemeralPublicKey\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\x12+\n" +
	"\x11encrypted_payload\x18\x05 \x01(\fR\x10encryptedPayload\x128\n" +
	"\x18attestation_binding_hash\x18\x06 \x01(\fR\x16attestationBindingHash\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\x12B\n" +
	"\vcompression\x18\b \x01(\x0e2 .cevell.wire.v1.CompressionCodecR\vcompression\x12o\n" +
	"\x12ecosystem_metadata\x18\t \x03(\v2@.cevell.wire.v1.EncryptedInferenceRequest.EcosystemMetadataEntryR\x11ecosystemMetadata\x1aD\n" +
	"\x16EcosystemMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe7\x01\n" +
	"\x17StreamingInferenceFrame\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\rR\x0esequenceNumber\x128\n" +
	"\n" +
	"frame_type\x18\x02 \x01(\x0e2\x19.cevell.wire.v1.FrameTypeR\tframeType\x12+\n" +
	"\x11encrypted_payload\x18\x03 \x01(\fR\x10encryptedPayload\x12\x19\n" +
	"\bauth_tag\x18\x04 \x01(\fR\aauthTag\x12!\n" +
	"\ftimestamp_ns\x18\x05 \x01(\x03R\vtimestampNs*\x86\x01\n" +
	"\vCipherSuite\x12\x1c\n" +
	"\x18CIPHER_SUITE_UNSPECIFIED\x10\x00\x12(\n" +
	"$CIPHER_SUITE_DHKEM_X25519_AES256_GCM\x10\x01\x12/\n" +
	"+CIPHER_SUITE_DHKEM_X25519_CHACHA20_POLY1305\x10\x02*V\n" +
	"\x10CompressionCodec\x12\x14\n" +
	"\x10COMPRESSION_NONE\x10\x00\x12\x14\n" +
	"\x10COMPRESSION_ZSTD\x10\x01\x12\x16\n" +
	"\x12COMPRESSION_SNAPPY\x10\x02*\xa9\x01\n" +
	"\tFrameType\x12\x1a\n" +
	"\x16FRAME_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FRAME_TYPE_TOKEN_DELTA\x10\x01\x12\x19\n" +
	"\x15FRAME_TYPE_COMPLETION\x10\x02\x12\x19\n" +
	"\x15FRAME_TYPE_STREAM_END\x10\x03\x12\x14\n" +
	"\x10FRAME_TYPE_ERROR\x10\x04\x12\x18\n" +
	"\x14FRAME_TYPE_HEARTBEAT\x10\x05B2Z0github.com/cevell/private-ai/pkg/proto/v1;wirev1b\x06proto3"

var (
	file_wire_proto_rawDescOnce sync.Once
	file_wire_proto_rawDescData []byte
)

func file_wire_proto_rawDescGZIP() []byte {
	file_wire_proto_rawDescOnce.Do(func() {
		file_wire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wire_proto_rawDesc), len(file_wire_proto_rawDesc)))
	})
	return file_wire_proto_rawDescData
}

var file_wire_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_wire_proto_goTypes = []any{
	(CipherSuite)(0),                  // 0: cevell.wire.v1.CipherSuite
	(CompressionCodec)(0),             // 1: cevell.wire.v1.CompressionCodec
	(FrameType)(0),                    // 2: cevell.wire.v1.FrameType
	(*EncryptedInferenceRequest)(nil), // 3: cevell.wire.v1.EncryptedInferenceRequest
	(*StreamingInferenceFrame)(nil),   // 4: cevell.wire.v1.StreamingInferenceFrame
	nil,                               // 5: cevell.wire.v1.EncryptedInferenceRequest.EcosystemMetadataEntry
}
var file_wire_proto_depIdxs = []int32{
	0, // 0: cevell.wire.v1.EncryptedInferenceRequest.cipher_suite:type_name -> cevell.wire.v1.CipherSuite
	1, // 1: cevell.wire.v1.EncryptedInferenceRequest.compression:type_name -> cevell.wire.v1.CompressionCodec
	5, // 2: cevell.wire.v1.EncryptedInferenceRequest.ecosystem_metadata:type_name -> cevell.wire.v1.EncryptedInferenceRequest.EcosystemMetadataEntry
	2, // 3: cevell.wire.v1.StreamingInferenceFrame.frame_type:type_name -> cevell.wire.v1.FrameType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_wire_proto_init() }
func file_wire_proto_init() {
	if File_wire_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wire_proto_rawDesc), len(file_wire_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_proto_goTypes,
		DependencyIndexes: file_wire_proto_depIdxs,
		EnumInfos:         file_wire_proto_enumTypes,
		MessageInfos:      file_wire_proto_msgTypes,
	}.Build()
	File_wire_proto = out.File
	file_wire_proto_goTypes = nil
	file_wire_proto_depIdxs = nil
}
